require 'action_controller'
require 'action_mailer'

require 'textris/base'
require 'textris/message'
require 'textris/delivery'
require 'textris/delivery/base'
require 'textris/delivery/test'
require 'textris/delivery/mail'
require 'textris/delivery/twilio'
